name: json_to_dart
description: "A Dart-based tool class."
publish_to: "none"
homepage: https://github.com/Matkurban/json_to_dart
version: 1.0.2
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  json_serializable: ^6.9.4
  shared_preferences: ^2.5.2
  flex_color_scheme: ^8.1.1
  toastification: ^2.3.0
  syntax_highlight: ^0.4.0
  package_info_plus: ^8.2.1
  flutter_json_view: ^1.1.5
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Light.ttf
