name: json_to_dart
description: "It is a Json tool for generating Dart code"
publish_to: "none"
version: 1.1.0
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: any
  get: ^4.7.2
  uuid: ^4.5.1
  animate_do: ^4.2.0
  url_launcher: ^6.3.1
  toastification: ^3.0.2
  cupertino_icons: ^1.0.8
  syntax_highlight: ^0.4.0
  flutter_json_view: ^1.1.5
  flex_color_scheme: ^8.2.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Light.ttf
