# AppId 的值唯一标识此应用。
# 不要在其他应用的安装程序中使用相同的 AppId 值。
app_id: 5B599538-42B1-4826-A479-AF079F21A65D
publisher: LeanFlutter
publisher_url: https://github.com/Matkurban/json_to_dart
display_name: JsonToDart
create_desktop_icon: true
locales:
  - zh
